### ISSUE TITLE
Change the balance display style in Accounts tab

### ISSUE THREAD

**Issue by nvllz** [Ivy-Apps/ivy-wallet#2712]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user, I would like to have the account balance value in the Accounts tab more visible and clear. 

![](https://github.com/Ivy-Apps/ivy-wallet/assets/110673332/f6f8789f-7d60-424c-9044-4b806fbcc8dc)
The current subscripted hundredths' style makes it a bit unreadable, especially for the balance value converted to the main currency. I personally have a little problem in seeing these small digits in the USD balance line.

### Why do you need it?

- to have the balance easily readable
- would fix the visibility for currency-converted line as shown above

### How do you imagine it?

I think it is as simple as making the hundredths value appear in line with and the same size as the other digits of the balance value. To make them look different, apply a light/thin font style as for the currency code

**Comment by ILIYANGERMANOV** [comment]
Hey @nvllz that's by design because the real account balance is the GBP value and the USD (subscripted) is how much is it in your main currency. Noted: for when redesigning the screen. cc @stefanilijev97 

Thanks for the feedback! I'll close the issue for now cuz we'll address it when redesigning accounts to M3

**Comment by ILIYANGERMANOV** [comment]
Ahaa, I understand now. I read between the lines cuz usually I do 3-4 things at the same time 😀 Apologies, reopening!

**Task:**
Make the `.89` and `.61` bigger.

**Comment by Adrin7113** [comment]
I'm on it

**Comment by Adrin7113** [comment]
![WhatsApp Image 2023-09-28 at 12 10 09](https://github.com/Ivy-Apps/ivy-wallet/assets/112411286/5830519d-0334-4ea8-996d-b1e5714945db)
is this how you wanted it?

**Comment by ILIYANGERMANOV** [comment]
To be fair, I try to apply the same rules from https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md for everyone. Feel free to suggest how we can improve our rules

**Comment by ILIYANGERMANOV** [comment]
No worries, it @Adrin7113 hasn't started it feel free to submit a PR with the fix - it looks good. Let's wait for @Adrin7113 to decide on the next steps 👍 

Thank you for your understanding and raising the issue @nvllz 🙏 I'm open to suggestions to streamline the processes so everyone is happy and contributing feels good and fair

**Comment by Adrin7113** [comment]
Oh the new version looks great. We can go with that?

**Comment by Adrin7113** [comment]
![WhatsApp Image 2023-09-28 at 21 54 31_d8622274](https://github.com/Ivy-Apps/ivy-wallet/assets/112411286/aa487790-e669-4078-8389-3118f8f2de5c)
Is this alright?

**Comment by Adrin7113** [comment]
Oooh sorry sorry got it. I'll get on that

**Comment by Adrin7113** [comment]
![WhatsApp Image 2023-09-29 at 19 53 17_5beb6b61](https://github.com/Ivy-Apps/ivy-wallet/assets/112411286/73287c28-36f4-4577-af7f-61942a28e6b9)
Sorry this took so long. I changed it to use a single Text.

**Comment by ILIYANGERMANOV** [comment]
> ![WhatsApp Image 2023-09-29 at 19 53 17_5beb6b61](https://user-images.githubusercontent.com/112411286/271632345-73287c28-36f4-4577-af7f-61942a28e6b9.jpg) Sorry this took so long. I changed it to use a single Text.

Hey, no rush - it should be formatted as "0.00" use the existing Ivy Wallet's `Double.format` extension. See how @nvllz did it in his commit, sth like that

**Comment by Adrin7113** [comment]
Oh okay okay I'll check that

**Comment by Adrin7113** [comment]
![WhatsApp Image 2023-09-30 at 20 04 45_2c5c12ec](https://github.com/Ivy-Apps/ivy-wallet/assets/112411286/8067d58f-49b9-4635-98d0-93d33de79925)
Applied the format function.

**Comment by Adrin7113** [comment]
> ![WhatsApp Image 2023-09-30 at 20 04 45_2c5c12ec](https://github.com/Ivy-Apps/ivy-wallet/assets/112411286/8067d58f-49b9-4635-98d0-93d33de79925)
> Applied the format function.

@ILIYANGERMANOV

**Comment by ILIYANGERMANOV** [comment]
Hey @Adrin7113 just raise a PR and let's discuss there. This way I can also review your code
